services:
  bridger:
    image: mastrogiovanni/bridger:v0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
      - 8000:8000
    command:
      - bridger
      - /app/config.yaml
      - dev:api-service:9000
    volumes:
      - ./config.yaml:/app/config.yaml
      - /home/user/.ssh/known_hosts:/root/.ssh/known_hosts
      - /home/user/.ssh/id_rsa:/root/.ssh/id_rsa
