services:
  bridger:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2345:2345
      - 1234:1234
    command:
      - bridger
      - /app/config.yaml
      - local:whoami:2345
      # - uat:calm:2345
      # - uat:db:1234
    volumes:
      - ./config.yaml:/app/config.yaml
      - /home/michele/.ssh/known_hosts:/root/.ssh/known_hosts
      - /home/michele/.ssh/id_rsa:/root/.ssh/id_rsa

