- name: dev
  hostname: user@192.168.0.1
  components:
    - type: kubernetes
      name: api-service
      service: api-service
      port: 8080
      bridge-port: 10001
    - type: kubernetes
      name: web-service
      service: web-service
      port: 80
      bridge-port: 10002
- name: staging
  hostname: user@staging.example.com
  components:
    - type: docker
      name: app
      service: app-container
      port: 8000
    - type: docker
      name: db
      service: database-container
      port: 5432
